version: '3.1'

services:

  nestjs_kysely_automock_db:
    image: postgres:16.1
    container_name: nestjs_kysely_automock_db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: postgres
      POSTGRES_DB: nestjs_kysely_automock_db
    ports:
      - 5432:5432

